// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SprintMonitor.API.Data;

#nullable disable

namespace SprintMonitor.API.Migrations
{
    [DbContext(typeof(SprintMonitorDbContext))]
    [Migration("20260418184123_AddTeamSizeToTeams")]
    partial class AddTeamSizeToTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SprintMonitor.API.Models.ImplementationFeasibility", b =>
                {
                    b.Property<int>("FeasibilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeasibilityId"));

                    b.Property<string>("AdoptionChallenges")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpectedBenefits")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IntegrationFeasibility")
                        .HasColumnType("bit");

                    b.Property<string>("IntegrationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MentorComments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("OperationalFeasibility")
                        .HasColumnType("bit");

                    b.Property<string>("OperationalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("OrganizationalFeasibility")
                        .HasColumnType("bit");

                    b.Property<string>("OrganizationalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OverallScore")
                        .HasColumnType("int");

                    b.Property<string>("ScalabilityConsiderations")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<bool>("TechnicalFeasibility")
                        .HasColumnType("bit");

                    b.Property<string>("TechnicalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FeasibilityId");

                    b.HasIndex("TeamId");

                    b.ToTable("ImplementationFeasibilities");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.Recommendation", b =>
                {
                    b.Property<int>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationId"));

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("AddressesRiskFactor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("SuggestedChange")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("WasApplied")
                        .HasColumnType("bit");

                    b.HasKey("RecommendationId");

                    b.HasIndex("AssessmentId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.RiskAssessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<int?>("ActualCompletedPoints")
                        .HasColumnType("int");

                    b.Property<int?>("ActualOutcome")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<int>("ExternalDependencies")
                        .HasColumnType("int");

                    b.Property<int>("MaxPossibleScore")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PlannedCommitment")
                        .HasColumnType("int");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.Property<int?>("SprintId")
                        .HasColumnType("int");

                    b.Property<int>("TeamAvailability")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("AssessmentId");

                    b.HasIndex("TeamId");

                    b.ToTable("RiskAssessments");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.RiskFactor", b =>
                {
                    b.Property<int>("FactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactorId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FactorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<decimal>("MetricValue")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<decimal?>("Threshold")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("FactorId");

                    b.HasIndex("AssessmentId");

                    b.ToTable("RiskFactors");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.RiskFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("ActualOutcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ActualPointsCompleted")
                        .HasColumnType("int");

                    b.Property<bool?>("ActualSpillover")
                        .HasColumnType("bit");

                    b.Property<int?>("ActualSpilloverPoints")
                        .HasColumnType("int");

                    b.Property<string>("AgreementLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackComments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImprovementSuggestions")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PredictedRisk")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RecommendationRating")
                        .HasColumnType("int");

                    b.Property<bool>("RecommendationsHelpful")
                        .HasColumnType("bit");

                    b.Property<int?>("SprintId")
                        .HasColumnType("int");

                    b.Property<bool>("UsedForCalibration")
                        .HasColumnType("bit");

                    b.Property<bool>("UserAgreement")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FeedbackId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("SprintId");

                    b.ToTable("RiskFeedbacks");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.Sprint", b =>
                {
                    b.Property<int>("SprintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SprintId"));

                    b.Property<int>("AddedPoints")
                        .HasColumnType("int");

                    b.Property<int>("CommittedPoints")
                        .HasColumnType("int");

                    b.Property<int>("CompletedPoints")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExternalDependencies")
                        .HasColumnType("int");

                    b.Property<bool>("HadSpillover")
                        .HasColumnType("bit");

                    b.Property<int>("RemovedPoints")
                        .HasColumnType("int");

                    b.Property<int>("SprintDuration")
                        .HasColumnType("int");

                    b.Property<string>("SprintName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeamAvailability")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TeamSize")
                        .HasColumnType("int");

                    b.HasKey("SprintId");

                    b.HasIndex("TeamId", "SprintName")
                        .IsUnique();

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeamSize")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.HasIndex("TeamName")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.TeamSetting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SettingId");

                    b.HasIndex("TeamId", "SettingKey")
                        .IsUnique();

                    b.ToTable("TeamSettings");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.ImplementationFeasibility", b =>
                {
                    b.HasOne("SprintMonitor.API.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.Recommendation", b =>
                {
                    b.HasOne("SprintMonitor.API.Models.RiskAssessment", "Assessment")
                        .WithMany("Recommendations")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.RiskAssessment", b =>
                {
                    b.HasOne("SprintMonitor.API.Models.Team", "Team")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.RiskFactor", b =>
                {
                    b.HasOne("SprintMonitor.API.Models.RiskAssessment", "Assessment")
                        .WithMany("Factors")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.RiskFeedback", b =>
                {
                    b.HasOne("SprintMonitor.API.Models.RiskAssessment", "Assessment")
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SprintMonitor.API.Models.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Assessment");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.Sprint", b =>
                {
                    b.HasOne("SprintMonitor.API.Models.Team", "Team")
                        .WithMany("Sprints")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.TeamSetting", b =>
                {
                    b.HasOne("SprintMonitor.API.Models.Team", "Team")
                        .WithMany("Settings")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.User", b =>
                {
                    b.HasOne("SprintMonitor.API.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.RiskAssessment", b =>
                {
                    b.Navigation("Factors");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("SprintMonitor.API.Models.Team", b =>
                {
                    b.Navigation("RiskAssessments");

                    b.Navigation("Settings");

                    b.Navigation("Sprints");
                });
#pragma warning restore 612, 618
        }
    }
}
